services:
  - type: web
    name: railway-app
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python core/manage.py migrate
    startCommand: gunicorn --chdir core core.wsgi:application